FROM gradle:8.5-jdk21 AS build
WORKDIR /home/gradle/src

COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle

COPY . .

RUN ./gradlew clean build -x test --no-daemon

# Etapa de empaquetado con JDK 21
FROM openjdk:21-jdk-slim
WORKDIR /app

COPY --from=build /home/gradle/src/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]

# FIN